name = "cb-site"
main = "worker.js"
compatibility_date = "2024-09-10"

[vars]
EMAIL_PROVIDER   = "mailchannels"
SUPPORT_TO_EMAIL = "support@chrisbrighouse.com"
SENDER_EMAIL     = "no-reply@chrisbrighouse.com"
SENDER_NAME      = "Downloads"
CORS_ORIGIN      = "https://www.chrisbrighouse.com"
