
import React from 'react';

const Footer: React.FC = () => {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="bg-gray-800 text-white">
      <div className="container mx-auto px-6 py-8">
        <div className="flex flex-col md:flex-row justify-between items-center">
          <div className="text-center md:text-left mb-4 md:mb-0">
            <div className="border-2 border-white px-3 py-1 inline-block">
                <h3 className="text-xl font-black italic tracking-tight">Chris Brighouse</h3>
            </div>
            <p className="mt-2 text-sm text-gray-400">AI Transformation & Product Management Consulting</p>
          </div>
          <div className="text-center md:text-right">
            <p className="text-sm text-gray-400">&copy; {currentYear} Chris Brighouse. All Rights Reserved.</p>
            <p className="text-xs text-gray-500 mt-1">Website code generated by Google Gemini.</p>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
